table Calculos

	measure 'Salidas Almacén' =
			
			CALCULATE (
			    SUM ( FactControlProyecto[Cantidad] ),
			    FactControlProyecto[SkIdClaseOrigen] = 10
			)

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cantidad OC' =
			
			SUMX (
			    FactCompras,
			    [Cantidad Comprada]
			        + IF (
			            [SkIdEstado] = 10024,
			            LOOKUPVALUE (
			                FactDevoluciones[Cantidad Devuelta],
			                FactDevoluciones[CompraInsumo], [CompraInsumo],
			                BLANK ()
			            ),
			            0
			        )
			)

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Traslados Entradas' =
			
			CALCULATE (
			    SUM ( FactControlProyecto[Cantidad] ),
			    FactControlProyecto[SkIdClaseOrigen] = 2
			)

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cantidad Asegurada' =
			
			IF (
			    ISINSCOPE ( FactCompras[Fecha OC] ),
			    BLANK (),
			    [Cantidad OC] + [Traslados Entradas] - [Devoluciones]
			)

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Reintegros =
			
			CALCULATE (
			    SUM ( FactControlProyecto[Cantidad] ),
			    FactControlProyecto[SkIdClaseOrigen] = 5
			)

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cantidad Consumida' =
			
			IF (
			    ISINSCOPE ( FactCompras[Fecha OC] ),
			    BLANK (),
			    [Salidas Almacén] + [Reintegros]
			)

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Devoluciones =
			
			SUMX (
			    FactCompras,
			    LOOKUPVALUE (
			        FactDevoluciones[Cantidad Devuelta],
			        FactDevoluciones[CompraInsumo], [CompraInsumo],
			        BLANK ()
			    )
			)

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Column
		isHidden
		formatString: 0
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition Calculos = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 61ed1bd207584d3ca7da45bd88cf83b1

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

