table DimItems

	column SkIdItems
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: SkIdItems

		annotation SummarizationSetBy = User

	column 'Item No'
		dataType: string
		summarizeBy: none
		sourceColumn: Item No

		annotation SummarizationSetBy = User

	column 'Item Descripcion'
		dataType: string
		summarizeBy: none
		sourceColumn: Item Descripcion

		annotation SummarizationSetBy = User

	column 'Item estado'
		dataType: string
		summarizeBy: none
		sourceColumn: Item estado

		annotation SummarizationSetBy = Automatic

	column SubCapitulo
		dataType: string
		summarizeBy: none
		sourceColumn: SubCapitulo

		annotation SummarizationSetBy = Automatic

	column Item
		dataType: string
		summarizeBy: none
		sourceColumn: Item

		annotation SummarizationSetBy = Automatic

	partition DimItems = m
		mode: import
		source =
				let
				    Source = Sql.Database("datamart.sincoerp.com,4263", "SincoMYTDW"),
				    ADP_DTM_DIM_Items = Source{[Schema="ADP_DTM_DIM",Item="Items"]}[Data],
				    ElegirColumnas = Table.SelectColumns(ADP_DTM_DIM_Items,{"SkIdItems", "Item No", "SubCapitulo", "Item Descripcion", "Item estado"}),
				    Item = Table.AddColumn(ElegirColumnas, "Item", each Text.Combine({[Item No], [Item Descripcion]}, " - "), type text)
				in
				    Item

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

