table DimItems

	column SkIdItems
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: SkIdItems

		annotation SummarizationSetBy = User

	column 'Item No'
		dataType: string
		summarizeBy: none
		sourceColumn: Item No

		annotation SummarizationSetBy = User

	column 'Item Descripcion'
		dataType: string
		summarizeBy: none
		sourceColumn: Item Descripcion

		annotation SummarizationSetBy = User

	column 'Item N° Descripción' = CONCATENATE(DimItems[Item No] , CONCATENATE(" - " , DimItems[Item Descripcion]))
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Unidad Medida'
		dataType: string
		summarizeBy: none
		sourceColumn: Unidad Medida

		annotation SummarizationSetBy = Automatic

	column 'Item estado'
		dataType: string
		summarizeBy: none
		sourceColumn: Item estado

		annotation SummarizationSetBy = Automatic

	column Item
		dataType: string
		summarizeBy: none
		sourceColumn: Item

		annotation SummarizationSetBy = Automatic

	partition DimItems = m
		mode: import
		source =
				let
				    Source = Sql.Database("datamart.sincoerp.com,4263", "SincoMYTDW"),
				    ADP_DTM_DIM_Items = Source{[Schema="ADP_DTM_DIM",Item="Items"]}[Data],
				    ElegirColumnas = Table.SelectColumns(ADP_DTM_DIM_Items,{"SkIdItems", "Item No", "SubCapitulo", "Item Descripcion", "Unidad Medida", "Item estado"}),
				    #"Inserted Merged Column" = Table.AddColumn(ElegirColumnas, "Merged", each Text.Combine({[Item No], [Item Descripcion]}, " - "), type text),
				    #"Merged Columns" = Table.CombineColumns(#"Inserted Merged Column",{"Merged", "SubCapitulo"},Combiner.CombineTextByDelimiter("  ", QuoteStyle.None),"Item")
				in
				    #"Merged Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

