table FactAjustes

	column SkIdProyecto
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: SkIdProyecto

		annotation SummarizationSetBy = Automatic

	column SkIdInsumo
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: SkIdInsumo

		annotation SummarizationSetBy = Automatic

	column Cantidad
		dataType: double
		summarizeBy: sum
		sourceColumn: Cantidad

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition FactAjustes = m
		mode: import
		source =
				let
				    Source = Sql.Database("datamart.sincoerp.com,4263", "SincoMYTDW"),
				    ADP_DTM_FACT_InventarioResumido = Source{[Schema="ADP_DTM_FACT",Item="InventarioResumido"]}[Data],
				    #"Filas filtradas" = Table.SelectRows(ADP_DTM_FACT_InventarioResumido, each ([Tipo] = "AI") and ([Documento] <> -10)),
				    #"Otras columnas quitadas" = Table.SelectColumns(#"Filas filtradas",{"SkIdProyecto", "SkIdInsumo", "Cantidad"})
				in
				    #"Otras columnas quitadas"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

