table FactDevoluciones

	column 'Cantidad Devuelta'
		dataType: double
		formatString: 0
		summarizeBy: none
		sourceColumn: Cantidad Devuelta

		annotation SummarizationSetBy = Automatic

	column CompraInsumo
		dataType: string
		summarizeBy: none
		sourceColumn: CompraInsumo

		annotation SummarizationSetBy = Automatic

	partition FactDevoluciones = m
		mode: import
		source =
				let
				    Source = Sql.Database("datamart.sincoerp.com,4263", "SincoMYTDW"),
				    ADP_DTM_FACT_Devoluciones = Source{[Schema="ADP_DTM_FACT",Item="Devoluciones"]}[Data],
				    ElegirColumnas = Table.SelectColumns(ADP_DTM_FACT_Devoluciones,{"SkIdProyecto", "SkIdInsumo", "Cantidad Devuelta", "Compra No"}),
				    CompraInsumo = Table.AddColumn(ElegirColumnas, "CompraInsumo", each Text.Combine({Text.From([Compra No], "es-CO"), Text.From([SkIdInsumo], "es-CO")}, ":"), type text),
				    Agrupar = Table.Group(CompraInsumo, {"SkIdProyecto", "SkIdInsumo", "Compra No", "CompraInsumo"}, {{"Cantidad Devuelta", each List.Sum([Cantidad Devuelta]), type nullable number}}),
				    QuitarCeros = Table.SelectRows(Agrupar, each ([Cantidad Devuelta] <> 0)),
				    ColumnasFinales = Table.SelectColumns(QuitarCeros,{"CompraInsumo", "Cantidad Devuelta"})
				in
				    ColumnasFinales

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

